### ISSUE TITLE
Firebase permission issue?

### ISSUE THREAD

**Issue by sam26880** [bruz/react-native-redux-groceries#13] opened 2016-08-13 15:47 UTC
https://www.dropbox.com/s/tqp515vejikbjah/Screenshot%202016-08-13%2011.46.50.png?dl=0

**Comment by bruz** [comment] 2016-08-22 06:18
Thanks for spotting this. I was able to reproduce it with a newly-created Firebase database, which appears to have security rules that require authentication by default now. You can get the app working by changing the security rules to:

``` javascript
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

I've updated the README to reflect needing to make that Firebase change.

**Comment by bruz** [comment] 2016-09-30 16:27
Closing this since I think the README update addresses it, but feel free to reopen if that doesn't fix it for you.

**Closed as completed by bruz** 2016-09-30 16:27 UTC
